### ISSUE TITLE
[Lesson 3] Image missing

### ISSUE THREAD

**Issue by cmaneu** [microsoft/generative-ai-for-beginners#103]
On the lesson 3, there is an image missing under "Hallucinations" section.

**Comment by rizwanshoukat3324** [comment]
Due to your internet speed image was not appaired in front of you.
![Github cooment](https://github.com/microsoft/generative-ai-for-beginners/assets/111968550/b92b9711-5896-450f-892d-ff7e06168dfe)

**Comment by koreyspace** [comment]
Thanks @rizwanshoukat3324 , we will look at using lower quality images to accommodate lower internet speeds

**Comment by cmaneu** [comment]
I'm not sure my issue was related to internet speeds....
![image](https://github.com/microsoft/generative-ai-for-beginners/assets/790974/1c150444-8389-4283-8ae4-21bff971173d)

**Comment by cmaneu** [comment]
@koreyspace you're already using webp here (image is 60Kb). The image path is a little weird.

**Comment by koreyspace** [comment]
Thanks for looking into this further @cmaneu , I will take a look at the image path to see if that is the source of the issue.

**Comment by leestott** [comment]
Cannot repo this issue on Codepaces or GitHub.dev as such closing the issue 

![image](https://github.com/microsoft/generative-ai-for-beginners/assets/2511341/55406462-5033-45b5-aab5-476240aca625)
