### ISSUE TITLE
Move images from lesson folder to media folder

### ISSUE THREAD

**Issue by john0isaac** [microsoft/generative-ai-for-beginners#105]
**Is your feature request related to a problem? Please describe.**
In the ninth exercise, all the images are in the main folder for the lesson while there is an images folder not all the images are inside it.

**Describe the solution you'd like**
Move all the images to the images folder, don't forget to change their path in the .md files or ipynb

**Additional context**
https://github.com/microsoft/generative-ai-for-beginners/tree/main/09-building-image-applications

**Comment by BheezPen** [comment]
I'm Self assigning myself to this issue.
