### ISSUE TITLE
OpenAI service access isn't for personal user

### ISSUE THREAD

**Issue by cutePanda123** [microsoft/generative-ai-for-beginners#122]
**Describe the bug**
The OpenAI service access form requires an enterprise user, which blocks personal users from learning the course. Can you please help share an instruction on how to get access? Thanks!

**To Reproduce**
1. Go to OpenAI service access form (https://customervoice.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7en2Ais5pxKtso_Pz4b1_xUOFA5Qk1UWDRBMjg0WFhPMkIzTzhKQ1dWNyQlQCN0PWcu)
2. Scroll down to 'Possible causes for a denied application'
3. See the requirements

**Expected behavior**
A personal user should be able to access the OpenAI service to learn this course and practice the coding tasks. 

**Screenshots**
<img width="901" alt="image" src="https://github.com/microsoft/generative-ai-for-beginners/assets/26092755/2bf07e72-d1bc-4672-99dd-6d7fc5de683e">

**Comment by softchris** [comment]
thanks for your comment, we'll investigate

**Comment by koreyspace** [comment]
Hi @cutePanda123 , we are working on converting this course to also use OpenAI API as well. In the meantime, you can complete the non code lessons if interested and also check out the code completed code in each README.
