### ISSUE TITLE
Lesson 9 Chinese Translation Wikipedia image error

### ISSUE THREAD

**Issue by john0isaac** [microsoft/generative-ai-for-beginners#159]
**Describe the bug**
The url for the Wikipedia image is wrong.

**Expected behavior**
Correct path for the image.

**Screenshots**
![image](https://github.com/microsoft/generative-ai-for-beginners/assets/64026625/34aa3f8f-4c07-471a-a694-7314951f1242)

https://microsoft.github.io/generative-ai-for-beginners/#/09-building-image-applications/translations/cn/README?wt.mc_id=academic-105485-koreyst&id=midjourney

Wrong URL
![image](https://github.com/microsoft/generative-ai-for-beginners/assets/64026625/26bd7a28-0e50-4cc6-b2cf-f2e12ec958ab)

Correct URL can be found in the English translation
`https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Rupert_Breheny_mechanical_dove_eca144e7-476d-4976-821d-a49c408e4f36.png/440px-Rupert_Breheny_mechanical_dove_eca144e7-476d-4976-821d-a49c408e4f36.png?WT.mc_id=academic-105485-koreyst
`

**Comment by leestott** [comment]
fixed in #162
