### ISSUE TITLE
1-introduction.ipynb - openai.ChatCompletion no longer supported in openai>=1.0.0

### ISSUE THREAD

**Issue by Jasperb3** [microsoft/generative-ai-for-beginners#160]
**Describe the bug**
1-introduction.ipynb fails to run Exercise 2 with the following error message:

APIRemovedInV1: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**To Reproduce**
1. Install locally or on codespace
2. Run 1-introduction.ipynb in VS Code
3. Complete Exercise 1 successfully
4. Error on Exercise 2

**Expected behavior**
OpenAI API key to be set up

**Screenshots**
<img width="843" alt="image" src="https://github.com/microsoft/generative-ai-for-beginners/assets/141338069/0b3cca03-d16d-482f-8e48-3dcd3d6a10a5">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Conda environment
 - openai==1.2.2

**Comment by leestott** [comment]
Fix applied in https://github.com/microsoft/generative-ai-for-beginners/pull/163

The Devcontainer and codespaces environment should run a post installation after the installation and install python libraries listed in requirements.txt 

Requirements 
ipywidgets==7.7.1
matplotlib==3.7.0
numpy==1.24.2
pandas==1.5.3
tqdm==4.64.0
python-dotenv==1.0.0
openai>=0.28.0
tiktoken
