### ISSUE TITLE
Improve the Foundation Models graph in module 2

### ISSUE THREAD

**Issue by ZePowerdiver** [microsoft/generative-ai-for-beginners#184]
In the video of module 2, at about 2:28, there is a picture/graph that helps support the explanation of Foundation models compared to Large Language Models. The image is not clear and it's hard to view the details, mostly the inner bubble.

1. Go to https://www.youtube.com/watch?v=J1mWzw0P74c
2. Fast Forward to 2 minutes 28 seconds of the video clip
3. See error

I would expect to be able to view the diagram and be able to read the text within it.

![image](https://github.com/microsoft/generative-ai-for-beginners/assets/54417940/c6405092-f1f8-42cc-bf8a-d441830ac5be)

 - Windows 10 Pro 22H2
 - Edge
 - Version 119.0.2151.58 (Official build) (64-bit)

**Comment by leestott** [comment]
@PabloNunes please see this issue in your video

**Comment by rondales** [comment]
> In the video of module 2, at about 2:28, there is a picture/graph that helps support the explanation of Foundation models compared to Large Language Models. The image is not clear and it's hard to view the details, mostly the inner bubble.
> 
> Steps to reproduce the behavior:
> 
> 1. Go to https://www.youtube.com/watch?v=J1mWzw0P74c
> 2. Fast Forward to 2 minutes 28 seconds of the video clip
> 3. See error
> 
> I would expect to be able to view the diagram and be able to read the text within it.
> 
> ![image](https://private-user-images.githubusercontent.com/54417940/283602087-c6405092-f1f8-42cc-bf8a-d441830ac5be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTU1NjUsIm5iZiI6MTcwMjY1NTI2NSwicGF0aCI6Ii81NDQxNzk0MC8yODM2MDIwODctYzY0MDUwOTItZjFmOC00MmNjLWJmOGEtZDQ0MTgzMGFjNWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE1NDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NmYwMWFiNjJhYjI2ZGMxNDUzOGU0YWZiYmI1YTc4NzY2NDljOWE3ZDdjMTZkYTVkMzZkY2EzZTM0ZDU0ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZsXxPnGL05vx3inUIrRZeGw3eLBQRQ5fDM545c7GRgQ)
> 
> * Windows 10 Pro 22H2
> * Edge
> * Version 119.0.2151.58 (Official build) (64-bit)
