### ISSUE TITLE
 the form that get access Azure OpenAI Service  is closed

### ISSUE THREAD

**Issue by DayDreammy** [microsoft/generative-ai-for-beginners#190]
**Describe the bug**
> For the coding lessons, we are using the Azure OpenAI Service. You will need access to the Azure OpenAI service and an API key to run this code. You can apply to get access by [completing this application](https://customervoice.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7en2Ais5pxKtso_Pz4b1_xUOFA5Qk1UWDRBMjg0WFhPMkIzTzhKQ1dWNyQlQCN0PWcu&culture=en-us&country=us&WT.mc_id=academic-105485-koreyst).

but when I open the link, I get "this form is closed"
![image](https://github.com/microsoft/generative-ai-for-beginners/assets/107911537/df62a9c4-4d3a-4e86-8854-6833cb7f583c)
**To Reproduce**

**Comment by omerfguzel-agu** [comment]
Hey, any updates?

**Comment by softchris** [comment]
> Hey, any updates?

@omerfguzel-agu correct link to form can be found on this page, https://azure.microsoft.com/en-us/products/ai-services/openai-service
