### ISSUE TITLE
Translation to Brazilian Portuguese

### ISSUE THREAD

**Issue by brunotech** [microsoft/generative-ai-for-beginners#199]
I've forked the project and started translating it into PT-BR, both the text and video dubbing.

[brunotech/generative-ai-for-beginners@main/01-introduction-to-genai/translations/pt-br](https://github.com/brunotech/generative-ai-for-beginners/tree/main/01-introduction-to-genai/translations/pt-br)

**Comment by glaucia86** [comment]
@brunotech just to update you.... I already translated the whole course
cc: @PabloNunes @softchris @koreyspace 


https://github.com/microsoft/generative-ai-for-beginners/issues/84

**Comment by koreyspace** [comment]
Translation Complete
