### ISSUE TITLE
Just starting. Can’t fork the repository 

### ISSUE THREAD

**Issue by alexkor75** [microsoft/generative-ai-for-beginners#200]
[**Describe](url) the bug**

**To Reproduce**
![IMG_2362](https://github.com/microsoft/generative-ai-for-beginners/assets/144994839/a1c4743d-f23c-4228-b3c3-744a76297b07)
![IMG_2362](https://github.com/microsoft/generative-ai-for-beginners/assets/144994839/cb25028d-e82d-4671-b38d-ce9cd1360651)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by koreyspace** [comment]
Hey @alexkor75 sorry to hear you are having problems. Can you check if you might have already forked this repo in the past?

**Comment by alexkor75** [comment]
Thanks for your reply

I didn’t really understand
Can you have a look at the screenshot.
May be I did save it.



Сб, 25 нояб. 2023 г. в 01:11, Korey Stegared-Pace ***@***.***
