### ISSUE TITLE
Add Korean Translation

### ISSUE THREAD

**Issue by FacerAin** [microsoft/generative-ai-for-beginners#213]
**Is your feature request related to a problem? Please describe.**
Thank you for creating a wonderful repository for training generative AI!
I would like to start a **translation project** to make this repository accessible and useful **for Korean** users as well.

**Describe the solution you'd like**
The following modules are planned for translation. 
Please let me know if you would like to translate any of them, and I will add your name to the list as a tag.
- [x] [README](https://github.com/microsoft/generative-ai-for-beginners) @FacerAin 
- [x] [Course Introduction - How to Take This Course](https://github.com/microsoft/generative-ai-for-beginners/blob/main/00-course-setup/README.md?WT.mc_id=academic-105485-koreyst) @FacerAin
- [x] [Introduction to Generative AI and LLMs](https://github.com/microsoft/generative-ai-for-beginners/blob/main/01-introduction-to-genai/README.md?WT.mc_id=academic-105485-koreyst) @FacerAin
- [x] [Exploring and comparing different LLMs](https://github.com/microsoft/generative-ai-for-beginners/blob/main/02-exploring-and-comparing-different-llms/README.md?WT.mc_id=academic-105485-koreyst) @Eeap 
- [x] [Using Generative AI Responsibly](https://github.com/microsoft/generative-ai-for-beginners/blob/main/03-using-generative-ai-responsibly/README.md?WT.mc_id=academic-105485-koreyst) @mreraser
- [x] [Understanding Prompt Engineering Fundamentals](https://github.com/microsoft/generative-ai-for-beginners/blob/main/04-prompt-engineering-fundamentals/README.md?WT.mc_id=academic-105485-koreyst) @FacerAin 
- [x] [Creating Advanced Prompts](https://github.com/microsoft/generative-ai-for-beginners/blob/main/05-advanced-prompts/README.md?WT.mc_id=academic-105485-koreyst) @FacerAin 
- [x] [Building Text Generation Applications](https://github.com/microsoft/generative-ai-for-beginners/blob/main/06-text-generation-apps/README.md?WT.mc_id=academic-105485-koreyst) @mreraser 
- [x] [Building Chat Applications](https://github.com/microsoft/generative-ai-for-beginners/blob/main/07-building-chat-applications/README.md?WT.mc_id=academic-105485-koreyst)  @FacerAin 
- [x] [Building Search Apps Vector Databases](https://github.com/microsoft/generative-ai-for-beginners/blob/main/08-building-search-applications/README.md?WT.mc_id=academic-105485-koreyst) @FacerAin
- [x] [Building Image Generation Applications](https://github.com/microsoft/generative-ai-for-beginners/blob/main/09-building-image-applications/README.md?WT.mc_id=academic-105485-koreyst) @FacerAin
- [x] [Building Low Code AI Applications](https://github.com/microsoft/generative-ai-for-beginners/blob/main/10-building-low-code-ai-applications/README.md?WT.mc_id=academic-105485-koreyst) @FacerAin
- [x] [Integrating External Applications with Function Calling](https://github.com/microsoft/generative-ai-for-beginners/blob/main/11-integrating-with-function-calling/README.md?WT.mc_id=academic-105485-koreyst) @FacerAin
- [x] [Designing UX for AI Applications](https://github.com/microsoft/generative-ai-for-beginners/blob/main/12-designing-ux-for-ai-applications/README.md?WT.mc_id=academic-105485-koreyst) @mreraser
- [x] [Continue Your Learning](https://github.com/microsoft/generative-ai-for-beginners/blob/main/13-continued-learning/README.md?WT.mc_id=academic-105485-koreyst) @FacerAin 

**Describe alternatives you've considered**

**Additional context**

**Comment by mreraser** [comment]
Hello @FacerAin! Can I participate in your project as well? I'll do my best! 
If I can choose a module, I would like to select 'Using Generative AI Responsibly' and 'Designing UX for AI Applications'. 
Thank you!

**Comment by Eeap** [comment]
Hello, @FacerAin
If there is no one who translate "Exploring and comparing different LLMs", I want to select it !
Thank you :)

**Comment by koreyspace** [comment]
Hi everyone, thanks for wanted to contributing a Korean Translation. Will get a reviewer once a PR is submitted. Good luck and let us know how we can support!

**Comment by FacerAin** [comment]
Thanks for your help! @mreraser 
I’m sorry for the late reply. 
Could you submit a PR to the `translation/ko` branch of [this repository](https://github.com/FacerAin/generative-ai-for-beginners/tree/translation/ko)? 
After review, we will proceed with a request to the original repository via one PR.

**Comment by mreraser** [comment]
Hello @FacerAin, if nobody translated [ch 5 : Understanding Prompt Engineering Fundamentals] can I additionally participate on?

**Comment by FacerAin** [comment]
> Hello @FacerAin, if nobody translated [ch 5 : Understanding Prompt Engineering Fundamentals] can I additionally participate on?

@mreraser 

Oops, **I’ve already done** the work but forgot to update the list 😭😭 **I’ve updated the post** with the chapter I’m working on. Could you please refer to it and let me know again?

Thank you so much for your contribution. ☺️

**Comment by mreraser** [comment]
> * [Building Text Generation Applications](https://github.com/microsoft/generative-ai-for-beginners/blob/main/06-text-generation-apps/README.md?WT.mc_id=academic-105485-koreyst)

OK, then can I translate [Building Text Generation Applications]?

**Comment by mreraser** [comment]
> > Hello @FacerAin, if nobody translated [ch 5 : Understanding Prompt Engineering Fundamentals] can I additionally participate on?
> 
> @mreraser
> 
> Oops, **I’ve already done** the work but forgot to update the list 😭😭 **I’ve updated the post** with the chapter I’m working on. Could you please refer to it and let me know again?
> 
> Thank you so much for your contribution. ☺️

OK, then can I translate [Building Text Generation Applications]?

**Comment by FacerAin** [comment]
@mreraser 
Of course! I’ll add it to the list above! Thank you ☺️
