### ISSUE TITLE
Azure OpenAI Service requires company subscription

### ISSUE THREAD

**Issue by notmaxx** [microsoft/generative-ai-for-beginners#215]
Hello,

I am trying to follow the guide and create Azure OpenAI service and get API key. For this I need to fill some Azure form (this one https://azure.microsoft.com/products/ai-services/openai-service?WT.mc_id=academic-105485-koreyst). This form requires you to represent some company. 
<img width="813" alt="image" src="https://github.com/microsoft/generative-ai-for-beginners/assets/18590450/18d5dffe-8fa8-4035-ad8d-226d33695b0f">

Is it possible to get access and pass the guide with personal email address?

Thank you

**Comment by jermainezhimin** [comment]
+1 This is a odd blocker for a open source tutorial

**Comment by koreyspace** [comment]
Hey @jermainezhimin  and @notmaxx , yes this unfortunately a requirement at the moment to manage the demand for the service. We also plan to support the course with OpenAI API's that don't have this requirement early next year!
