### ISSUE TITLE
Typo in Knowledge Check section of 05-advanced-prompts'

### ISSUE THREAD

**Issue by tony21921** [microsoft/generative-ai-for-beginners#217]
**Describe the bug**
There is a typo in the Knowledge Check section of the 05-advanced-prompts file. The options are currently numbered, but it seems they should be labeled as A, B, C, etc. 

**To Reproduce**
1. Go to '05-advanced-prompts'
2. Scroll down to 'Knowledge Check section'
3. See error in the options list

**Expected behavior**
The options should be labeled as 1, 2, 3, etc. But there are B, C following 2, 3.

**Screenshots**
![image](https://github.com/microsoft/generative-ai-for-beginners/assets/46182461/6d06cbf9-0492-4509-8170-b29f76f1f2c7)

**Desktop (please complete the following information):**
 - Not applicable

**Smartphone (please complete the following information):**
 - Not applicable

**Additional context**
I would like to work on this fix.

**Comment by koreyspace** [comment]
@tony21921 please submit a PR for this
