### ISSUE TITLE
Review 04 Prompt Engineering Fundamentals

### ISSUE THREAD

**Issue by chrisxfire** [microsoft/generative-ai-for-beginners#218]
In the below section, the second row (1 cue) and third row (2 cues) seem to only have one cue:

![image](https://github.com/microsoft/generative-ai-for-beginners/assets/70714090/54dd924b-cbbe-48c9-b8d5-9c4463b9db8d)

Is this correct?

**Comment by koreyspace** [comment]
Thanks for reporting @chrisxfire , assigning to lesson owner @nitya to make any needed changes.

**Comment by nitya** [comment]
@chrisxfire @koreyspace just got back from OOO and will take a look today. At the very least, this is a great callout to make the documentation clearer so thank you for the review!
