### ISSUE TITLE
First code example does not work with Azure OpenAI

### ISSUE THREAD

**Issue by johnbatty** [microsoft/generative-ai-for-beginners#223]
**Describe the bug**

The introduction [states that the code examples will use Azure OpenAI](https://github.com/microsoft/generative-ai-for-beginners/blob/main/00-course-setup/README.md?WT.mc_id=academic-105485-koreyst#lessons-and-technical-requirements). 

However the very first code example [Exercise 2: OpenAI API Key Setup](https://github.com/microsoft/generative-ai-for-beginners/blob/main/04-prompt-engineering-fundamentals/1-introduction.ipynb) uses the (non-Azure) OpenAI API directly, which doesn't work for an Azure OpenAI deployment.

**To Reproduce**

Run [Exercise 2: OpenAI API Key Setup](https://github.com/microsoft/generative-ai-for-beginners/blob/main/04-prompt-engineering-fundamentals/1-introduction.ipynb) using an Azure OpenAI endpoint URL/key - it fails with an exception.

**Expected behavior**

The example to work with Azure OpenAI.

I expect that this needs:
- A description of the environment variables to set for Azure OpenAI.
- Possibly modified code to use the [Azure OpenAI API variations](https://github.com/openai/openai-python/#microsoft-azure-openai)?

**Comment by koreyspace** [comment]
I believe this is by design but @nitya please review to see if we can clear this up or also add Azure Open AI support for this lesson to avoid confusion

**Comment by webr5214** [comment]
Related, the first lesson instructs the user to save their API key as a codespaces secret, but this lesson doesn't tell how to retrieve the secret in the .env file. Would have saved some time to know it's: OPENAI_API_KEY=${SECRET_NAME}

**Comment by johnbatty** [comment]
It looks like this has been resolved via another PR: https://github.com/microsoft/generative-ai-for-beginners/pull/188
I'll close my PR.
