### ISSUE TITLE
Chapter 06 video is private

### ISSUE THREAD

**Issue by fabianMendez** [microsoft/generative-ai-for-beginners#226]
**Describe the bug**
The video on [chapter 06](https://github.com/microsoft/generative-ai-for-beginners/blob/main/06-text-generation-apps/README.md) is private: https://www.youtube.com/watch?v=5jKHzY6-4s8

**To Reproduce**
1. Go to [chapter 06](https://github.com/microsoft/generative-ai-for-beginners/blob/main/06-text-generation-apps/README.md)
2. Click on the image/video
3. Youtube says the video is private

**Expected behavior**
Video should be public

**Comment by benmcmaster** [comment]
Chapter 7's video is also private :(

**Comment by koreyspace** [comment]
This has been fixed now, thanks for reporting @benmcmaster and @fabianMendez
