### ISSUE TITLE
Course incorrectly refers to Llama as open source

### ISSUE THREAD

**Issue by 094459** [microsoft/generative-ai-for-beginners#227]
**Describe the bug**

Throughout the course, it refers to the Llama LLM as "open source" - this is not factually correct.

**To Reproduce**

NA

**Expected behavior**

Provide an updated and accurate description of Llama models - they are proprietary

**Screenshots**

NA

**Desktop (please complete the following information):**

NA

**Smartphone (please complete the following information):**

NA

**Additional context**

https://blog.opensource.org/metas-llama-2-license-is-not-open-source/

**Comment by koreyspace** [comment]
Hi @094459 , thanks for flagging this and providing a source. Unless I overlooked it, the source you provided does not provide any alternative naming/category. If you have suggestions or educational sources that provide this, happy to review. We will consider a change if it still provides beginner learners with a good way to compare and understand the differences between LLMs.

**Comment by 094459** [comment]
It should be changed as it is very misleading to developers - so its not really acceptable to leave as is. If you want suggestions, then just removing "open source" typically works, as it is in effect a proprietary licence.

**Comment by koreyspace** [comment]
We will make note that the labelling it "Open Source" is a discussion in the community with a link to the resource you shared. Looking at the various educational resources and model libraries out there, they all list Llama2 as open source.  It would be more confusing to learners if we were not aligned with other resources they will use. 

As a community we need to come to a greater consensus if open weights = open source and if the definition of open source needs to be reviewed in the age of LLMs.
