### ISSUE TITLE
Typo in read me description

### ISSUE THREAD

**Issue by wkotesh** [microsoft/generative-ai-for-beginners#234]
**Describe the bug**
Typo in Read Me Description 

**To Reproduce**
1. Go to the 'Read Me.md' section
2. Scroll down to '**Want to learn more?** section
3. See a highlighted typo in the below sentence. It should be "levelling"
         _After completing this course, check out our [Generative AI Learning collection](https://aka.ms/genai-collection?WT.mc_id=academic-105485-koreyst) to continue **leveling** up your Generative AI knowledge!_

**Expected behavior**
its should be "**levelling**" instead of leveling

**Screenshots**
![image](https://github.com/microsoft/generative-ai-for-beginners/assets/36853775/f21ef8bf-f7d3-435c-8b25-96815f895aec)

**Additional context**
I would like to work on this fix.

**Comment by koreyspace** [comment]
Fixed, thanks for the call out @wkotesh
