### ISSUE TITLE
APIConnectionError in the first Jupyter notebook, lesson 4

### ISSUE THREAD

**Issue by webr5214** [microsoft/generative-ai-for-beginners#239]
I forked the repository to run in GitHub Codespaces. I am loading my API key from a codespaces secret into the .env file. When I run the first code cell that uses the openai module in lesson 4, I get an http error. I tested with a print statement to make sure the OpenAI client is receiving my API key.

I tested with a curl command to see if I could access the openai api from within Codespaces and received the expected result.

curl https://api.openai.com/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer API_KEY " -d '{"model": "gpt-3.5-turbo",  "messages": [{"role": "user", "content": "Say this is a test!"}], "temperature": 0.7}'

Which makes me think it's a Jupyter environment problem.

Here's the error message:
![codespaces_lesson4](https://github.com/microsoft/generative-ai-for-beginners/assets/152835941/0cc60046-d223-4c9d-a0ca-133115b60900)

**Comment by yankeeshcn** [comment]
Hello, i have got same issue when run Exercise 2, 
![Ex2-error](https://github.com/microsoft/generative-ai-for-beginners/assets/45564413/e4a7100a-92d5-454f-a6c6-3ad34a6d6e26)
I used latest openai package version 1.61. 
I have checked the requirements.txt and downgrade openai from 1.61 to 0.28.0 and got another error. with below picture 
![Ex2-error-openai0 28 0](https://github.com/microsoft/generative-ai-for-beginners/assets/45564413/f79dde98-81dd-44bf-9efb-e0c30088f81a)
Do you have any idea?

**Comment by koreyspace** [comment]
Thanks for reporting, will take a look and let you know if we need any additional information!

**Comment by nitya** [comment]
I just walked through the notebook for Lesson 4 right now. **I believe that has been updated now to use the Azure OpenAI provider key/endpoint vs. OpenAI** which might be a reason why the call to the OpenAI API works from command-line, but the code fails.

I believe there is an OpenAI-specific set of exercises planned for the lessons. _But for now, you will need to use an Azure OpenAI endpoint_. If you have issues with that, can you please update this with new details? 

cc @koreyspace

**Comment by yuguangmao** [comment]
Hello, i have got same issue when run Exercise 2,

**Comment by yuguangmao** [comment]
Hello, i have got a same issue when run Exercise 2

**Comment by yuguangmao** [comment]
Hello, i have got a same issue when run Exercise 2
curll is ok
`
curl "https://kuncloud.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-02-15-preview" \
  -H "Content-Type: application/json" \
  -H "api-key: b23bf538e8b84a07806006e4491dddbfbadkey" \
  -d "{
  \"messages\": [{\"role\":\"system\",\"content\":\"You are an AI assistant that helps people find information.\"}],
  \"max_tokens\": 800,
  \"temperature\": 0.7,
  \"frequency_penalty\": 0,
  \"presence_penalty\": 0,
  \"top_p\": 0.95,
  \"stop\": null
}"
`
if i run python code in jupypter notebook , got a error 
`
import os
from openai import AzureOpenAI

client = AzureOpenAI(
  azure_endpoint = "https://kuncloud.openai.azure.com/", 
  api_key="b23bf538e8b84a07806006e4491dddbfbadkey",  
  api_version="2024-02-15-preview"
)

message_text = [{"role":"system","content":"You are an AI assistant that helps people find information."}]
completion = client.chat.completions.create(
  model="gpt-35-turbo", 
  messages = message_text,
  temperature=0.7,
  max_tokens=800,
  top_p=0.95,
  frequency_penalty=0,
  presence_penalty=0,
  stop=None
)
`
`---------------------------------------------------------------------------
ConnectError                              Traceback (most recent call last)
File /lib/python3.11/site-packages/httpx/_transports/default.py:69, in map_httpcore_exceptions()
     68 try:
---> 69     yield
     70 except Exception as exc:

File /lib/python3.11/site-packages/httpx/_transports/default.py:233, in HTTPTransport.handle_request(self, request)
    232 with map_httpcore_exceptions():
--> 233     resp = self._pool.handle_request(req)
    235 assert isinstance(resp.stream, typing.Iterable)

File /lib/python3.11/site-packages/httpcore/_sync/connection_pool.py:216, in ConnectionPool.handle_request(self, request)
    215     self._close_connections(closing)
--> 216     raise exc from None
    218 # Return the response. Note that in this case we still have to manage
    219 # the point at which the response is closed.

File /lib/python3.11/site-packages/httpcore/_sync/connection_pool.py:196, in ConnectionPool.handle_request(self, request)
    194 try:
    195     # Send the request on the assigned connection.
--> 196     response = connection.handle_request(
    197         pool_request.request
    198     )
    199 except ConnectionNotAvailable:
    200     # In some cases a connection may initially be available to
    201     # handle a request, but then become unavailable.
    202     #
    203     # In this case we clear the connection and try again.

File /lib/python3.11/site-packages/httpcore/_sync/connection.py:99, in HTTPConnection.handle_request(self, request)
     98     self._connect_failed = True
---> 99     raise exc
    101 return self._connection.handle_request(request)

File /lib/python3.11/site-packages/httpcore/_sync/connection.py:76, in HTTPConnection.handle_request(self, request)
     75 if self._connection is None:
---> 76     stream = self._connect(request)
     78     ssl_object = stream.get_extra_info("ssl_object")

File /lib/python3.11/site-packages/httpcore/_sync/connection.py:122, in HTTPConnection._connect(self, request)
    121 with Trace("connect_tcp", logger, request, kwargs) as trace:
--> 122     stream = self._network_backend.connect_tcp(**kwargs)
    123     trace.return_value = stream

File /lib/python3.11/site-packages/httpcore/_backends/sync.py:205, in SyncBackend.connect_tcp(self, host, port, timeout, local_address, socket_options)
    200 exc_map: ExceptionMapping = {
    201     socket.timeout: ConnectTimeout,
    202     OSError: ConnectError,
    203 }
--> 205 with map_exceptions(exc_map):
    206     sock = socket.create_connection(
    207         address,
    208         timeout,
    209         source_address=source_address,
    210     )

File /lib/python311.zip/contextlib.py:155, in _GeneratorContextManager.__exit__(self, typ, value, traceback)
    154 try:
--> 155     self.gen.throw(typ, value, traceback)
    156 except StopIteration as exc:
    157     # Suppress StopIteration *unless* it's the same exception that
    158     # was passed to throw().  This prevents a StopIteration
    159     # raised inside the "with" statement from being suppressed.

File /lib/python3.11/site-packages/httpcore/_exceptions.py:14, in map_exceptions(map)
     13     if isinstance(exc, from_exc):
---> 14         raise to_exc(exc) from exc
     15 raise

ConnectError: [Errno 23] Host is unreachable

The above exception was the direct cause of the following exception:

ConnectError                              Traceback (most recent call last)
File /lib/python3.11/site-packages/openai/_base_client.py:918, in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
    917 try:
--> 918     response = self._client.send(
    919         request,
    920         stream=stream or self._should_stream_response_body(request=request),
    921         **kwargs,
    922     )
    923 except httpx.TimeoutException as err:

File /lib/python3.11/site-packages/httpx/_client.py:914, in Client.send(self, request, stream, auth, follow_redirects)
    912 auth = self._build_request_auth(request, auth)
--> 914 response = self._send_handling_auth(
    915     request,
    916     auth=auth,
    917     follow_redirects=follow_redirects,
    918     history=[],
    919 )
    920 try:

File /lib/python3.11/site-packages/httpx/_client.py:942, in Client._send_handling_auth(self, request, auth, follow_redirects, history)
    941 while True:
--> 942     response = self._send_handling_redirects(
    943         request,
    944         follow_redirects=follow_redirects,
    945         history=history,
    946     )
    947     try:

File /lib/python3.11/site-packages/httpx/_client.py:979, in Client._send_handling_redirects(self, request, follow_redirects, history)
    977     hook(request)
--> 979 response = self._send_single_request(request)
    980 try:

File /lib/python3.11/site-packages/httpx/_client.py:1015, in Client._send_single_request(self, request)
   1014 with request_context(request=request):
-> 1015     response = transport.handle_request(request)
   1017 assert isinstance(response.stream, SyncByteStream)

File /lib/python3.11/site-packages/httpx/_transports/default.py:232, in HTTPTransport.handle_request(self, request)
    220 req = httpcore.Request(
    221     method=request.method,
    222     url=httpcore.URL(
   (...)
    230     extensions=request.extensions,
    231 )
--> 232 with map_httpcore_exceptions():
    233     resp = self._pool.handle_request(req)

File /lib/python311.zip/contextlib.py:155, in _GeneratorContextManager.__exit__(self, typ, value, traceback)
    154 try:
--> 155     self.gen.throw(typ, value, traceback)
    156 except StopIteration as exc:
    157     # Suppress StopIteration *unless* it's the same exception that
    158     # was passed to throw().  This prevents a StopIteration
    159     # raised inside the "with" statement from being suppressed.

File /lib/python3.11/site-packages/httpx/_transports/default.py:86, in map_httpcore_exceptions()
     85 message = str(exc)
---> 86 raise mapped_exc(message) from exc

ConnectError: [Errno 23] Host is unreachable

The above exception was the direct cause of the following exception:

APIConnectionError                        Traceback (most recent call last)
Cell In[5], line 11
      9 # Send a completion call to generate an answer
     10 start_phrase = 'Write a tagline for an ice cream shop. '
---> 11 response = client.completions.create(model=deployment_name, prompt=start_phrase, max_tokens=10)
     12 print(start_phrase+response.choices[0].text)

File /lib/python3.11/site-packages/openai/_utils/_utils.py:275, in required_args.<locals>.inner.<locals>.wrapper(*args, **kwargs)
    273             msg = f"Missing required argument: {quote(missing[0])}"
    274     raise TypeError(msg)
--> 275 return func(*args, **kwargs)

File /lib/python3.11/site-packages/openai/resources/completions.py:506, in Completions.create(self, model, prompt, best_of, echo, frequency_penalty, logit_bias, logprobs, max_tokens, n, presence_penalty, seed, stop, stream, suffix, temperature, top_p, user, extra_headers, extra_query, extra_body, timeout)
    478 @required_args(["model", "prompt"], ["model", "prompt", "stream"])
    479 def create(
    480     self,
   (...)
    504     timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
    505 ) -> Completion | Stream[Completion]:
--> 506     return self._post(
    507         "/completions",
    508         body=maybe_transform(
    509             {
    510                 "model": model,
    511                 "prompt": prompt,
    512                 "best_of": best_of,
    513                 "echo": echo,
    514                 "frequency_penalty": frequency_penalty,
    515                 "logit_bias": logit_bias,
    516                 "logprobs": logprobs,
    517                 "max_tokens": max_tokens,
    518                 "n": n,
    519                 "presence_penalty": presence_penalty,
    520                 "seed": seed,
    521                 "stop": stop,
    522                 "stream": stream,
    523                 "suffix": suffix,
    524                 "temperature": temperature,
    525                 "top_p": top_p,
    526                 "user": user,
    527             },
    528             completion_create_params.CompletionCreateParams,
    529         ),
    530         options=make_request_options(
    531             extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
    532         ),
    533         cast_to=Completion,
    534         stream=stream or False,
    535         stream_cls=Stream[Completion],
    536     )

File /lib/python3.11/site-packages/openai/_base_client.py:1200, in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
   1186 def post(
   1187     self,
   1188     path: str,
   (...)
   1195     stream_cls: type[_StreamT] | None = None,
   1196 ) -> ResponseT | _StreamT:
   1197     opts = FinalRequestOptions.construct(
   1198         method="post", url=path, json_data=body, files=to_httpx_files(files), **options
   1199     )
-> 1200     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))

File /lib/python3.11/site-packages/openai/_base_client.py:889, in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
    880 def request(
    881     self,
    882     cast_to: Type[ResponseT],
   (...)
    887     stream_cls: type[_StreamT] | None = None,
    888 ) -> ResponseT | _StreamT:
--> 889     return self._request(
    890         cast_to=cast_to,
    891         options=options,
    892         stream=stream,
    893         stream_cls=stream_cls,
    894         remaining_retries=remaining_retries,
    895     )

File /lib/python3.11/site-packages/openai/_base_client.py:942, in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
    939 log.debug("Encountered Exception", exc_info=True)
    941 if retries > 0:
--> 942     return self._retry_request(
    943         options,
    944         cast_to,
    945         retries,
    946         stream=stream,
    947         stream_cls=stream_cls,
    948         response_headers=None,
    949     )
    951 log.debug("Raising connection error")
    952 raise APIConnectionError(request=request) from err

File /lib/python3.11/site-packages/openai/_base_client.py:1013, in SyncAPIClient._retry_request(self, options, cast_to, remaining_retries, response_headers, stream, stream_cls)
   1009 # In a synchronous context we are blocking the entire thread. Up to the library user to run the client in a
   1010 # different thread if necessary.
   1011 time.sleep(timeout)
-> 1013 return self._request(
   1014     options=options,
   1015     cast_to=cast_to,
   1016     remaining_retries=remaining,
   1017     stream=stream,
   1018     stream_cls=stream_cls,
   1019 )

File /lib/python3.11/site-packages/openai/_base_client.py:942, in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
    939 log.debug("Encountered Exception", exc_info=True)
    941 if retries > 0:
--> 942     return self._retry_request(
    943         options,
    944         cast_to,
    945         retries,
    946         stream=stream,
    947         stream_cls=stream_cls,
    948         response_headers=None,
    949     )
    951 log.debug("Raising connection error")
    952 raise APIConnectionError(request=request) from err

File /lib/python3.11/site-packages/openai/_base_client.py:1013, in SyncAPIClient._retry_request(self, options, cast_to, remaining_retries, response_headers, stream, stream_cls)
   1009 # In a synchronous context we are blocking the entire thread. Up to the library user to run the client in a
   1010 # different thread if necessary.
   1011 time.sleep(timeout)
-> 1013 return self._request(
   1014     options=options,
   1015     cast_to=cast_to,
   1016     remaining_retries=remaining,
   1017     stream=stream,
   1018     stream_cls=stream_cls,
   1019 )

File /lib/python3.11/site-packages/openai/_base_client.py:952, in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
    942         return self._retry_request(
    943             options,
    944             cast_to,
   (...)
    948             response_headers=None,
    949         )
    951     log.debug("Raising connection error")
--> 952     raise APIConnectionError(request=request) from err
    954 log.debug(
    955     'HTTP Request: %s %s "%i %s"', request.method, request.url, response.status_code, response.reason_phrase
    956 )
    958 try:

APIConnectionError: Connection error.`

**Comment by yuguangmao** [comment]
这个错误的原因一般都是因为防火墙或者权限的原因，无法访问api；请检查

**Comment by yuguangmao** [comment]
The reason for this error is usually that a firewall or permissions are blocking access to the api; please check: 1) the correct api access permissions; 2) that there is no firewall between the client application and the api.
