### ISSUE TITLE
04-prompt-engineering-fundamentals -> fabrications-example

### ISSUE THREAD

**Issue by bartoszgolebiowski** [microsoft/generative-ai-for-beginners#246]
https://github.com/microsoft/generative-ai-for-beginners/blob/main/04-prompt-engineering-fundamentals/README.md#fabrications-example
"""
This also reinforces [Responsible AI guidelines](https://www.microsoft.com/ai/responsible-ai?WT.mc_id=academic-105485-koreyst) from a terminology perspective, removing terms that may also be considered offensive or non-inclusive in some contexts.
"""

 [Responsible AI guidelines](https://www.microsoft.com/ai/responsible-ai?WT.mc_id=academic-105485-koreyst)  does not work.
 I could not find a valid link.
 If someone can find a working link please update it.
 
 Thanks!

**Comment by BethanyJep** [comment]
Hello, does this [[Link](https://www.microsoft.com/en-us/ai/responsible-ai?WT.mc_id=academic-105485-koreyst&rtc=1)](https://www.microsoft.com/en-us/ai/responsible-ai?WT.mc_id=academic-105485-koreyst&rtc=1), work for you?

**Comment by nitya** [comment]
@bartoszgolebiowski - agree with @BethanyJep 
I can still see the link above. When I click that it goes to this site:

**You can also visiit that directly by going to https://microsoft.com/ai/responsible-ai**

![Screen Shot 2024-02-06 at 3 48 49 PM](https://github.com/microsoft/generative-ai-for-beginners/assets/279083/f9d1ff85-ddba-4cd6-a896-ffb23f1529b9)

@koreyspace - I think this issue can be closed if all agree.
