### ISSUE TITLE
Link to the video in Modules 08 and 09 is broken

### ISSUE THREAD

**Issue by stefanpems** [microsoft/generative-ai-for-beginners#260]
Hello. The link to the video in Modules 08 and 09 is broken. 
I tried to search these videos in the MS Reactor channel in YouTube but I could'nt find it (I found a lot of great and inherent content there but these 2 short and recent videos seem to be missing).
Can you add the link to these 2 videos?

**Comment by BethanyJep** [comment]
Hello @stefanpems, the videos are currently being worked on by the team and are yet to go live, once they are done, it will be updated
