### ISSUE TITLE
Accessing Azure Open AI Resources as a PERSON

### ISSUE THREAD

**Issue by sekaroz** [microsoft/generative-ai-for-beginners#261]
Hello, 
First of all, I think this course is a treasure and I am so happy that I have found it. 

I want to declare first that I am a complete nooby (medical background) who is looking to take this course and learn more about Generative AI. I saw that I must have access to Azure Open AI Resources, but as I was making the request I have noticed that I must be an employee in a company or I must have a working company! 

I am a way too far to work/have a company. So what can I do to start learning? 

Please help me 

Thanks in advance

**Comment by koreyspace** [comment]
Hi @sekaroz ,at the moment being a part of a company is required for access to Azure Open AI. We have on our roadmap for this quarter to support the Open AI APIs this as well : https://github.com/microsoft/generative-ai-for-beginners/discussions/237

The first 6 lessons do not require Azure Open AI access so I would suggest starting there. We will keep you updated when release the new material.
