### ISSUE TITLE
[Spanish Translation] README.md Lessions 02, 03 and 05.

### ISSUE THREAD

**Issue by abrilurena** [microsoft/generative-ai-for-beginners#295]
This issue is to translate README.md Lessions 02, 03 and 05 into spanish.

The structure of the translation should follow other translations like https://github.com/microsoft/generative-ai-for-beginners/tree/main/01-introduction-to-genai/translations/es-mx

**Comment by abrilurena** [comment]
Thank you for taking this one @icebeam7 and @ppiova!

**Comment by icebeam7** [comment]
Hello, I just wanted to check if the issue is marked as completed because the translations were merged or not at all, thank you! :)
