### ISSUE TITLE
Video unavailable(already solved)

### ISSUE THREAD

**Issue by SkyLancer34** [microsoft/generative-ai-for-beginners#314]
https://learn.microsoft.com/_themes/docs.theme/master/en-us/_themes/global/video-embed.html?id=36c6795a-e63c-46dd-8d69-df8bbe6e7bc9?WT.mc_id=academic-105485-koreyst
the page pointed to by this link prompts "video unavailable".
(lesson 1)
thx.

**Comment by SkyLancer34** [comment]
It opened normally just after I sent this issue...sry for that,ignore this post pls.

**Comment by KarmaBlack1** [comment]
Gp
