### ISSUE TITLE
Can I use the content of as course material for my education website for kids?

### ISSUE THREAD

**Issue by sailxjx** [microsoft/generative-ai-for-beginners#319]
**Is your feature request related to a problem? Please describe.**
I have a education website for kids https://codekidz.ai, which focus in teaching kids programming and AI, taught by virtual AI teacher. I am currently looking for high-quality course content and partners. The "generative-ai-for-beginners" has a great course structure and content. I hope to create a simplified version of the course on my website (for example, removing steps like installing Jupyter). Who should I discuss this matter with?

**Comment by koreyspace** [comment]
Hi @sailxjx , sound very interesting. Please reach out to me at koreyst [at] microsoft [dot] com

**Comment by sailxjx** [comment]
Hey @koreyspace, as we've discussed previously, I'll try to incorporate the content into our education website for kids, the first version will surely have many issues, let's optimize it together. If you have more suggestions, such as how to add executable sections on the web (preferably offline), feel free to discuss with me, my email is jingxin at codekidz.ai.

I will close this issue, but will keep following up.
