### ISSUE TITLE
Errata in closed captions for the videos 

### ISSUE THREAD

**Issue by indcoder** [microsoft/generative-ai-for-beginners#321]
**Describe the bug**
Looks like the user captions in the accompanying videos need to be reviewed by the speakers. 

As an example, in the first video of the course  [Exploring and comparing different LLMs](https://microsoft.github.io/generative-ai-for-beginners/#/02-exploring-and-comparing-different-llms/README?wt.mc_id=academic-105485-koreyst&id=exploring-and-comparing-different-llms), while Pablo is mentioning **labelling** of data, the user captions in the video is displaying **walling** of data 

<img width="778" alt="image" src="https://github.com/microsoft/generative-ai-for-beginners/assets/2099300/d27d2358-e2e0-4376-8707-5c46a2cffcc4">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by indcoder** [comment]
Another instance in the same video?
What are space forts ?😊 I think Pablo mentioned "base forks"

<img width="824" alt="image" src="https://github.com/microsoft/generative-ai-for-beginners/assets/2099300/35890b64-c902-4b79-9437-b78d87d6c7de">

**Comment by indcoder** [comment]
Dolly or DALL-E

<img width="746" alt="image" src="https://github.com/microsoft/generative-ai-for-beginners/assets/2099300/d2a77de7-5a04-4f53-bd53-47b555715ac3">

**Comment by koreyspace** [comment]
Thanks for reporting @indcoder , I believe these are auto-generated. We have plans to re-shoot our videos and will make sure the captions are fully accurate.
