### ISSUE TITLE
Pin OpenAI package to 0.28 version or update codebase for openai>=1.0.0

### ISSUE THREAD

**Issue by indcoder** [microsoft/generative-ai-for-beginners#336]
**Describe the bug**
We need to either pin the openai python package to 0.28 or update the Python codebase to work with  openai>=1.0.0

<img width="921" alt="image" src="https://github.com/microsoft/generative-ai-for-beginners/assets/2099300/71bfd26c-f75e-4fd2-88a5-3a48a6237e2c">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by koreyspace** [comment]
Great point @indcoder , before I change this, I wanted to see if you would like to create a PR for this yourself?

**Comment by indcoder** [comment]
Hi @koreyspace . Perhaps we have to split this in two PRs: 

1. Immediate PR so as to not disrupt any ongoing bootcamps: Pin the OpenAI dependency to 0.28 so that existing code does not break. 
2. Detailed PR: Update the requirement to openai>=1.0.0 and verify all the Python across the 18 lessons work with this update. This will also have to be done in conjunction w/ #335
