### ISSUE TITLE
Add Korean translation

### ISSUE THREAD

**Issue by mel-f-dev** [microsoft/generative-ai-for-beginners#345]
**Feature Request: Contribution to Translate Repository to Korean for AI Enthusiasts**

**Problem Description:**
The lack of Korean language support for the repository hinders Korean individuals interested in AI.

**Solution Description:**
I propose translating the repository into Korean with a mentor-led team by June or July. We plan to initiate a contributhon with our mentees who are eager to learn about gen AI and contribute to open-source systems. This timeline allows for thorough drafting, multiple reviews, and ensures high-quality translation efforts.

**Alternative Considerations:**
Using machine translation tools may compromise accuracy, cultural relevance, and engagement for Korean readers. Our multiple review system mitigates these risks.

**Additional Context:**
A Korean translation fosters inclusivity, enhancing understanding and participation in the AI community.

**Comment by koreyspace** [comment]
Hey @mel-f-dev - korean translations have been added for the V1 of the course! This was not done by machine translators but a community contribution. Enjoy, please create a pull request if you can see where the content can be improved. 

You can find them in the translations folder of each lesson: https://github.com/microsoft/generative-ai-for-beginners/tree/main/01-introduction-to-genai/translations/ko
