### ISSUE TITLE
Tracking links break pdf generation with docsifytopdf

### ISSUE THREAD

**Issue by ekoome** [microsoft/generative-ai-for-beginners#351]
**Describe the bug**
I get the following error when running `npm run convert`.
Alternatively, please generate a pdf in the repo. Thanks.

INFO:
Build with settings:

{
  "pathToStatic": "static",
  "mainMdFilename": "main.md",
  "removeTemp": true,
  "contents": "docs/_sidebar.md",
  "pathToPublic": "./pdf/readme.pdf",
  "pdfOptions": {
    "format": "A4"
  },
  "emulateMedia": "print",
  "pathToDocsifyEntryPoint": "."
}

ERROR:
run error

Error: ENOENT: no such file or directory, lstat '/home/me/generative-ai-for-beginners/01-introduction-to-genai/README.md?WT.mc_id=academic-105485-koreyst'

**To Reproduce**
1. Run 'npm run convert'
2. See error

**Expected behavior**
Generate pdf

**Comment by eriknue** [comment]
.
