### ISSUE TITLE
Japanese version needs to be updated to version 2

### ISSUE THREAD

**Issue by yoshioterada** [microsoft/generative-ai-for-beginners#364]
Need to check the updated the places

## Identify corrections or additions

It seems that the following entry is added.

### 0. [Top Page](https://github.com/yoshioterada/generative-ai-for-beginners/blob/main/README.md)

![Image URL](https://microsoft.github.io/generative-ai-for-beginners/images/repo-thubmnail2.png?WT.mc_id=academic-105485-koreyst)

```
The above Image URL 

### 18 Lessons teaching everything you need to know to start building Generative AI applications

# Generative AI for Beginners (Version 2) - A Course

| 13 | [Securing Your Generative AI Applications](https://oai.azure.com/portal/e7de87023b2348239a0363cb4aa49f6f/13-securing-ai-applications/README.md?WT.mc_id=academic-105485-koreyst) | Learn: The threats and risks to AI systems and methods to secure these systems. | [Learn More](https://aka.ms/genai-collection?WT.mc_id=academic-105485-koreyst) |
| 14 | [The Generative AI Application Lifecycle](https://oai.azure.com/portal/e7de87023b2348239a0363cb4aa49f6f/14-the-generative-ai-application-lifecycle/README.md?WT.mc_id=academic-105485-koreyst) | Learn: The tools and metrics to manage the LLM Lifecycle and LLMOps | [Learn More](https://aka.ms/genai-collection?WT.mc_id=academic-105485-koreyst) |
| 15 | [Retrieval Augmented Generation (RAG) and Vector Databases](https://oai.azure.com/portal/e7de87023b2348239a0363cb4aa49f6f/15-rag-and-vector-databases/README.md?WT.mc_id=academic-105485-koreyst) | Build: An application using a RAG Framework to retrieve embeddings from a Vector Databases | [Learn More](https://aka.ms/genai-collection?WT.mc_id=academic-105485-koreyst) |
| 16 | [Open Source Models and Hugging Face](https://oai.azure.com/portal/e7de87023b2348239a0363cb4aa49f6f/16-open-source-models/README.md?WT.mc_id=academic-105485-koreyst) | Build: An application using open source models available on Hugging Face | [Learn More](https://aka.ms/genai-collection?WT.mc_id=academic-105485-koreyst) |
| 17 | [AI Agents](https://oai.azure.com/portal/e7de87023b2348239a0363cb4aa49f6f/17-ai-agents/README.md?WT.mc_id=academic-105485-koreyst) | Build: An application using an AI Agent Framework | [Learn More](https://aka.ms/genai-collection?WT.mc_id=academic-105485-koreyst) |
| 18 | [Fine-Tuning LLMs](https://oai.azure.com/portal/e7de87023b2348239a0363cb4aa49f6f/18-fine-tuning/README.md?WT.mc_id=academic-105485-koreyst) | Learn: The what, why and how of fine-tuning LLMs | [Learn More](https://aka.ms/genai-collection?WT.mc_id=academic-105485-koreyst) |

🌟 Special thanks
Special thanks to [**John Aziz**](https://www.linkedin.com/in/john0isaac/) for creating all of the GitHub Actions and workflows

- [**NEW** Cybersecurity for Beginners](https://github.com/microsoft/Security-101??WT.mc_id=academic-96948-sayoung)
```

**Comment by koreyspace** [comment]
Yes @yoshioterada these have been added, thanks for logging this issue.

**Comment by sailxjx** [comment]
Seems a lot of demand related to multilingualism. Since this course is about generative AI, why not leverage the capabilities of LLM to implement automatic multilingual support? 
I've created an online chat version of this course that supports any conversation, and the content can also be conveniently translated into various languages. Additionally, you can get a virtual teacher who can supplement the lesson with real-time knowledge and is capable of voice chatting. I am looking for official support.

<img width="1531" alt="Screenshot 2024-06-03 at 09 07 06" src="https://github.com/microsoft/generative-ai-for-beginners/assets/909853/64bcf16d-922a-4a47-9566-8b890882387b">

**Comment by sailxjx** [comment]
@yoshioterada I don't understand Japanese, so I can't judge the content translated by the LLM. Based on my feelings about the Chinese translation from LLM, I find that about 90% of the content is acceptable, while the other 10% feels a bit too archaic, not like the terms modern people would use, but the meaning is correct.
I think maybe by adjusting the prompt, we can make its translation closer to real life. After all, manual translation requires a lot of time, and even after LLM's translation, manual review still takes up considerable effort.
For me, as long as the professional technical vocabulary is translated correctly, some minor grammatical issues are unimportant.
Finally thank you for the time dedicated to open source.

**Comment by sailxjx** [comment]
@yoshioterada 跟进一下，我已经在自己的网站上发布了这项课程的多语言版本，如果你有时间能否帮我看看日文翻译的质量

https://codekidz.ai/lesson-intro/generative-a-362093

可以通过底部的多语言菜单进行切换
