### ISSUE TITLE
Please, create a step-by-step guide to set up an Azure OpenAI FREE account (for the API key)

### ISSUE THREAD

**Issue by bringonthestorm** [microsoft/generative-ai-for-beginners#412]
**Is your feature request related to a problem? Please describe.**
In chapter 4, it seems to me that we need An Azure OpenAI API key. But setting up a FREE Azure OpenAI service is not straightforward. Also, it seems Azure needs a company email, not hotmail, gmail and the likes. What if I'm a freelancer?

**Describe the solution you'd like**
I'd like to see a step-by-step guide to set up a proper free Azure OpenAI account so that we can use the API key.

**Describe alternatives you've considered**
I've looked for the official Microsoft guide, but it's not satisfactory. It's confusing and cumbersome.

**Additional context**

**Comment by koreyspace** [comment]
Hey @bringonthestorm - there is no Azure OpenAI Free Account unfortnately. We have created instructions to use the OpenAI API (non-Azure). You do receive some free credits when creating an account there and do not require a busineess account. https://github.com/microsoft/generative-ai-for-beginners/tree/main/00-course-setup
