### ISSUE TITLE
There is a bad link in `11-integrating-with-function-calling/README.md`

### ISSUE THREAD

**Issue by doggy8088** [microsoft/generative-ai-for-beginners#425]
https://github.com/microsoft/generative-ai-for-beginners/blob/main/11-integrating-with-function-calling/README.md

> We recommend you to use the [included notebook](/11-integrating-with-function-calling/Lesson11-FunctionCalling.ipynb) if you want to run the below scenario. You can also just read along as we're trying to illustrate a problem where functions can help to address the problem.

The link `included notebook` is point to `/11-integrating-with-function-calling/Lesson11-FunctionCalling.ipynb` which do not exist.

**Comment by koreyspace** [comment]
issue resolved
