### ISSUE TITLE
In Chapter 15 - Where its inserting data in cosmos database ?

### ISSUE THREAD

**Issue by Abhijitk914** [microsoft/generative-ai-for-beginners#524]
**Describe the bug**
I was trying to implement the example given in chapter 15 -> notebook-rag-vector-databases.ipynb

I can see we are connecting to cosmos database and container but at the end of the script no any data is getting inserted into container / database.  In this vector database sample code when its going to retrieve / insert data from cosmos database ?

If it's not inserting in database? then what's the use of cosmos DB here?

**Expected behavior**
My assumption is it should insert data in cosmos db. Which is not happening in this code.

**Comment by koreyspace** [comment]
Hey @BethanyJep can you review this when you get a chance?

**Comment by BethanyJep** [comment]
Let me check and update. But ideally, we are to use CosmosDB as our Vector database to store the embeddings.
