### ISSUE TITLE
Azure OpenAI example uses OpenAI APIs

### ISSUE THREAD

**Issue by alfredodeza** [microsoft/generative-ai-for-beginners#53]
The notebook example for Azure Open AI (https://github.com/microsoft/generative-ai-for-beginners/blob/main/07-building-chat-applications/notebook-azure-openai.ipynb) is using OpenAI APIs and does not seem to demonstrate how to use it with Azure Open AI Service as the title mentions.

So this would need to get updated to either change the title to say "OpenAI" only, or update the code examples to match Azure Open AI Service

**Comment by leestott** [comment]
fix https://github.com/microsoft/generative-ai-for-beginners/pull/72 @koreyspace
