### ISSUE TITLE
.gitignore should ignore downloaded files of sample 08-building-search-applications

### ISSUE THREAD

**Issue by merklbe1SICKAG** [microsoft/generative-ai-for-beginners#536]
**Describe the bug**
in sample 08-building-search-applications the script (transcript_download.py) downloads data from youtube and stores is in subdirectory within the sample. However this is data which does not belong to the version control, hence there should be an entry in .gitignore.

**To Reproduce**
1. Go to 08-building-search-applications
2. build the example, download dependencies with pip etc
3. start the example via the prepare_transcripts_ai_show.sh
4. this downloads file to 08-building-search-applications/scripts/transcripts_the_ai_show/
5. git shows the downloaded files as U, however they should be ignored

**Expected behavior**
downloaded files should be ignored in git.

**Comment by koreyspace** [comment]
Thanks for reporting and the PR. I have tagged @gloveboxes to review as the lesson owner.
