### ISSUE TITLE
Chapter 4 link to Chat Playground doesn't work

### ISSUE THREAD

**Issue by vkolencik** [microsoft/generative-ai-for-beginners#538]
**Describe the bug**
In the chapter 4 in [Concept: Foundation Models
](https://github.com/microsoft/generative-ai-for-beginners/blob/main/04-prompt-engineering-fundamentals/README.md?WT.mc_id=academic-105485-koreyst#concept-foundation-models), there's a link to Chat Playground ([link](https://oai.azure.com/playground?WT.mc_id=academic-105485-koreyst)), but when going there I'm redirected to https://oai.azure.com/portal.

**To Reproduce**
1. Go to https://github.com/microsoft/generative-ai-for-beginners/blob/main/04-prompt-engineering-fundamentals/README.md?WT.mc_id=academic-105485-koreyst#concept-foundation-models
2. Click on "Chat Playground"
3. Log in to Microsoft account
4. You're redirected to Azure portal

**Expected behavior**
You see Chat Playground

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser Chrome
 - Version 126.0.6478.178 (Official Build) (64-bit)

**Additional context**
It seems like the resource related to Chat Playground was removed. I couldn't find an alternate link that would work.

**Comment by koreyspace** [comment]
Hey @nitya when you get the chance can your review this? I think the direct link has changed or at least the flow to getting directly to the playground via a logged in account has changed.
