### ISSUE TITLE
breaking openai library update in 09-building-image-applications

### ISSUE THREAD

**Issue by bmerkle** [microsoft/generative-ai-for-beginners#544]
**Describe the bug**
There are some breaking changes in openai library between version 0.28.x and version 1.x.
In sample 09-building-image-applications the requirements.txt does not specify any version.
Using pip pulls the most recent openai library (aka some 1.x version)
However the python code is still on version 0.28.x which results in invalid code.

The pull request fixes the python code and documentation:
- rename of openai.error.InvalidRequestError into openai.InvalidRequestError

**To Reproduce**
1. sample 09-building-image-applications
2. install python libraries via pip
3. open python files, shows invalid code

**Expected behavior**
Code, documentation and libraries shall be in sync.

**Comment by koreyspace** [comment]
Thanks for the fix @bmerkle , in review!
