### ISSUE TITLE
Build Search Application [The scale settings of account deployment is deprecated since API version '2023-05-01', please use 'sku' instead.]

### ISSUE THREAD

**Issue by mettyoung** [microsoft/generative-ai-for-beginners#574]
While doing the assignment, I encountered error. What version/sku should i use?

```
az cognitiveservices account deployment create \
    --name semantic-video-openai \
    --resource-group  semantic-video-search \
    --deployment-name text-embedding-ada-002 \
    --model-name text-embedding-ada-002 \
    --model-version "2"  \
    --model-format OpenAI \
    --scale-settings-scale-type "Standard"

```

**The scale settings of account deployment is deprecated since API version '2023-05-01', please use 'sku' instead.**

<img width="1335" alt="image" src="https://github.com/user-attachments/assets/04fd1ebf-42f5-4560-8a1c-50f7825ec9e1">

**Comment by bmerkle** [comment]
I think with API Version 2023-05-01 you have to use sku,
https://learn.microsoft.com/en-us/rest/api/aiservices/accountmanagement/deployments/create-or-update?view=rest-aiservices-accountmanagement-2023-05-01&tabs=HTTP

The documentation needs to be fixed here
