### ISSUE TITLE
Video on first lesson doesn't work

### ISSUE THREAD

**Issue by juanjojulian** [microsoft/generative-ai-for-beginners#62]
**Describe the bug**
Video on lesson 1 "Introduction to Generative AI and Large Language Models" doesn't work, YouTube says it's private.
**To Reproduce**
1. Go to https://github.com/microsoft/generative-ai-for-beginners/blob/main/01-introduction-to-genai/README.md
2. Click on YouTube video: https://youtu.be/vf_mZrn8ibc
3. See error

**Expected behavior**
Expected to access the video at YouTube

**Screenshots**
![CleanShot 2023-10-31 at 09 12 42](https://github.com/microsoft/generative-ai-for-beginners/assets/43988825/3f497134-c862-4a22-bd9c-ec5ceeecbf08)

**Desktop (please complete the following information):**
 - OS: MacOS 14
 - Browser Safari
 - Version 17

**Comment by leestott** [comment]
Content is now live @juanjojulian
