### ISSUE TITLE
How to embed the videos of this tutorial?

### ISSUE THREAD

**Issue by sailxjx** [microsoft/generative-ai-for-beginners#628]
I have been following this repo since it was first released and have incorporated its content into a series of courses on my educational platform.

https://codekidz.ai/lesson-intro/generative-a-362093

The videos in the tutorial were provided with address that could be embedded using an iframe, so I embedded them in the course and it worked very well, you can chat with AI while watching the video.

However, I found that the video address has now been changed to a webpage under the Microsoft domain, and due to domain restrictions, it is no longer possible to embed these videos on other websites. And I hope to continue updating the latest course modules to my platform.

I carefully read the project's license to confirm if I can use the content, and I have had email and online meeting communication with Korey to ensure that I can use the content, and I provide free access to the content on my website.

So is there a way to find an embeddable video link now, or any alternative method? Please also let me know if the content is no longer open sourced for free for other reasons.

**Comment by koreyspace** [comment]
Hey @sailxjx nice to see you again! It is probably best to embed the YT videos: https://www.youtube.com/watch?v=lFXQkBvEe0o&list=PLlrxD0HtieHj2nfK54c62lcs3-YSTx3Je

**Comment by sailxjx** [comment]
@koreyspace thank you for your help, I've just replaced all the videos with the youtube links, now it works very well. https://codekidz.ai/lesson-intro/generative-a-362093
