### ISSUE TITLE
Getting Started with this course instructions are using a different repo

### ISSUE THREAD

**Issue by colinrippeymangata** [microsoft/generative-ai-for-beginners#74]
In this page:

https://github.com/microsoft/generative-ai-for-beginners/blob/main/00-course-setup/README.md

The instructions at step:

https://github.com/microsoft/generative-ai-for-beginners/blob/main/00-course-setup/README.md#how-to-run-locally-on-your-computer

Ask to execute the following:

`git clone http://github.com/microsoft/ai-for-beginners
cd ai-for-beginners
conda env create --name ai4beg --file .devcontainer/environment.yml
conda activate ai4beg
`
Is this the correct repo to clone?

**Comment by leestott** [comment]
@colinrippeymangata fix being applied https://github.com/microsoft/generative-ai-for-beginners/pull/75
