### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by softchris** [microsoft/generative-ai-for-beginners#83]
**Is your feature request related to a problem? Please describe.**
People benefit from reading content in their own language

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by madebygps** [comment]
Depending on the timeline, I could help here.

**Comment by DarioChele** [comment]
I could help here. Just tell me what to do, and I'll do my best..

**Comment by Marcelasabogue** [comment]
@softchris On it
