### ISSUE TITLE
Add Portugese translation

### ISSUE THREAD

**Issue by softchris** [microsoft/generative-ai-for-beginners#84]
**Is your feature request related to a problem? Please describe.**
People benefit from learning in their own language

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by softchris** [comment]
@glaucia86 sounds like you're working on this one then. Thanks for your help :)

**Comment by jdubois** [comment]
Thanks for idea @softchris ! I just assigned @glaucia86 to the ticket and we're both excited about it

**Comment by glaucia86** [comment]
I will create a PR and start to translate this workshop to Portuguese and then with some code samples using JavaScript/TypeScript

**Comment by koreyspace** [comment]
@glaucia86  we have plans to do the entire course projects using JS/TS. Will ping you to discuss what you have already done and see what is left to add.

**Comment by glaucia86** [comment]
> @glaucia86 we have plans to do the entire course projects using JS/TS. Will ping you to discuss what you have already done and see what is left to add.


No problem, @koreyspace. You can count on me and also our JavaScript Advocacy for any engagement related to JS/TS for the project.
