### ISSUE TITLE
Suggest new lessons, tell us what you want to see

### ISSUE THREAD

**Issue by softchris** [microsoft/generative-ai-for-beginners#87]
**Is your feature request related to a problem? Please describe.**
Tell us what you want to see

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GeneAIisHere** [comment]
Test

**Comment by abidlabs** [comment]
Very cool course! Would it be possible to add a section on how to create Gradio applications from the machine learning models / apis in each chapter? Gradio is pretty widely used framework to build machine learning-related GUIs and I think many students would find it exciting to be able to interact with their models through a GUI.

**Comment by PratyushChauhan** [comment]
A module on RAG would be nice.

**Comment by softchris** [comment]
> A module on RAG would be nice.

@PratyushChauhan yes, that's definitely something we want to add, thanks for suggesting

**Comment by softchris** [comment]
> Very cool course! Would it be possible to add a section on how to create Gradio applications from the machine learning models / apis in each chapter? Gradio is pretty widely used framework to build machine learning-related GUIs and I think many students would find it exciting to be able to interact with their models through a GUI.
> 
> If there is interest, I'm happy to open up a PR to add this content to one of the chapters, perhaps chapter 9?

@koreyspace

**Comment by koreyspace** [comment]
> Very cool course! Would it be possible to add a section on how to create Gradio applications from the machine learning models / apis in each chapter? Gradio is pretty widely used framework to build machine learning-related GUIs and I think many students would find it exciting to be able to interact with their models through a GUI.
> 
> If there is interest, I'm happy to open up a PR to add this content to one of the chapters, perhaps chapter 9?

Hey @abidlabs , great suggestion! Would love to see some Gradio frontends for sure. Let's start with Chapter 9. Happy to review the PR and give you suggestions when you are done. Feel free to ping me on the Discord as well if you have any questions.

**Comment by PratyushChauhan** [comment]
> > A module on RAG would be nice.
> 
> Great suggestion, we are adding that early next year!

cool, what framework?
