### ISSUE TITLE
Missing Link from Lesson 11

### ISSUE THREAD

**Issue by john0isaac** [microsoft/generative-ai-for-beginners#94]
Under **Assignment** and **Code Challenge** the first element in the list ends with the word here but there is no hyperlink or url after it rather the link to the parameters is down below.

I think we should remove the word here or add another link to it.

Screenshot from Lesson 11 Readme:
![image](https://github.com/microsoft/generative-ai-for-beginners/assets/64026625/216f7f75-d762-4102-bedd-fd782e8bc254)

Screenshot from Lesson 11 notebook
![image](https://github.com/microsoft/generative-ai-for-beginners/assets/64026625/88305a8a-6365-4c31-af36-aa72e138f7df)

**Comment by leestott** [comment]
@koreyspace see issue above and suggestion for addition to exercise 11.

**Comment by BajiraoXD** [comment]
I would like to work on this issue. pls assign

**Comment by koreyspace** [comment]
Assigned to @BajiraoXD
