### ISSUE TITLE
Environment File Not Found error

### ISSUE THREAD

**Issue by OppoResearchIndia** [microsoft/generative-ai-for-beginners#98]
**Describe the bug**
After cloning the repo, when i tried to create the environment. I am getting this error. 
EnvironmentFileNotFound: '/home/notebook/code/personal/IN008915/generative-ai-for-beginners/.devcontainer/environment.yml' file not found

**Comment by leestott** [comment]
@nitya see issue above based on devcontainer.

**Comment by mapplezq** [comment]
I encountered the same problem.

**Comment by andrehe001** [comment]
same for me, just tried it but environment.yml file is missing.

**Comment by wangsy1983** [comment]
+1

**Comment by leestott** [comment]
In your project folder, and use the command 
conda env create -f environment.yml 
to create the environment. 

Alternatively, you can use the command 
conda env update -f environment.yml 
to update an existing environment with the dependencies.

**Comment by softchris** [comment]
does this updated text solve your problem? https://github.com/microsoft/generative-ai-for-beginners/tree/main/00-course-setup#installing-miniconda-optional-step  @wangsy1983 @andrehe001 @mapplezq @OppoResearchIndia

**Comment by softchris** [comment]
text updated to mention how to create environment.. Please reopen if it's still unclear
